name: Check test and code linting
on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v3.0.0

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
        - python-version: "3.8"
          tox: min
        - python-version: "3.9"
        - python-version: "3.10"
        - python-version: "3.11"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox codecov
      - name: Run tests
        run: tox -e ${{ matrix.tox || 'py' }}
